pipeline {
    agent any
environment {
    CI = 'true'
    HOME = '.'
    npm_config_cache = 'npm-cache'
  }
  stages {
    
    stage('Test and Build') {
      
          steps {
	    echo 'Running Tests..'
            bat 'npm run test'
          }
        }
    stage('Deploy') {
       steps {
         echo 'Deploying....'
       }
    }
    
}
}
