pipeline {
    agent any
environment {
    CI = 'true'
    HOME = '.'
    npm_config_cache = 'npm-cache'
  }
  stages {
    stage('Install Packages') {
      steps {
	/*echo 'Run pre-install'
	bat 'npm run preinstall' */     
	echo 'Install Packages..'
        bat 'npm install'
	/*echo 'Prepare for test'
	bat 'npm run pretest'*/
      }
    }
    stage('Test and Build') {
      parallel {
        stage('Run Tests') {
          steps {
	    echo 'Running Tests..'
            bat 'npm test -- a --watchAll=false --testMatch "**/src/**/*.test.js'
           /* echo ' Running test cleanup'
            bat 'npm run test:clean'*/
          }
        }
        stage('Create Build Artifacts') {
          steps {
	    echo 'Building Artifacts..'
            bat 'npm run build'
          }
        }
      }
    }
    stage('Deploy') {
       steps {
         echo 'Deploying....'
	 bat 'xcopy build D:\\reactjs-my-app /e /Y ' 
       }
    }
    
    }
    post { 
                success {  
                    dir('D:\\reactjs-my-app') {
                            bat 'npm start'
                        }
                }
            }
}
