pipeline {
    agent any
environment {
    CI = 'true'
    HOME = '.'
    npm_config_cache = 'npm-cache'
  }
  stages {
    stage('Install Packages') {
      steps {
	echo 'Install Packages..'
        bat 'npm clean-install'
      }
    }
    stage('Test and Build') {
      
          steps {
	    echo 'Running Tests..'
            bat 'npm test -- a --watchAll=false --testMatch "**/src/**/*.test.js'
          }
        }
    stage('Deploy') {
       steps {
         echo 'Deploying....'
       }
    }
    
}
}
